### ISSUE TITLE
panic: av_extend_guts() negative count

### ISSUE THREAD

**Issue by eserte** [stevan/p5-mop-redux#160]
The latest mop at CPAN (mop-0.03-TRIAL) fails with perl 5.23.6. See http://www.cpantesters.org/cpan/report/8132b358-ad47-11e5-9f21-26bde0bfc7aa for a sample report.

Might be related with https://rt.perl.org/Public/Bug/Display.html?id=126472

**Comment by stevan** [comment]
I really should delete this module from CPAN, it is no longer valid and should not be used, all development is now doing towards https://github.com/stevan/p5-mop instead

**Comment by eserte** [comment]
Fair enough. I stumbled over it because the distribution was listed as possible regression victim of perl 5.23.6: http://analysis.cpantesters.org/beforemaintrelease?pair=5.22.1:5.23.6

**Comment by stevan** [comment]
I have scheduled it for removal from CPAN, the PAUSE server says it should be deleted by Jan. 3
